name: scheduled-backup

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
    steps:
      - uses: actions/checkout@v4

      - name: Archive repository
        run: tar -czf repo-backup.tar.gz .

      - name: Upload to S3
        if: env.S3_BUCKET != ''
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp repo-backup.tar.gz s3://$S3_BUCKET/$(date +%F)-repo-backup.tar.gz

      - name: Store as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo-backup
          path: repo-backup.tar.gz
